version: "3.8"

services:
  plants-redis:
    image: redis:7
    container_name: plants_redis
    restart: always

  plants-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: plants_backend
    restart: always
    ports:
      - "5001:5000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      - plants-redis

  plants-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: ${REACT_APP_API_URL}
        REACT_APP_API_KEY: ${REACT_APP_API_KEY}
        REACT_APP_AUTH_DOMAIN: ${REACT_APP_AUTH_DOMAIN}
        REACT_APP_PROJECT_ID: ${REACT_APP_PROJECT_ID}
        REACT_APP_STORAGE_BUCKET: ${REACT_APP_STORAGE_BUCKET}
        REACT_APP_MESSAGING_SENDER_ID: ${REACT_APP_MESSAGING_SENDER_ID}
        REACT_APP_APP_ID: ${REACT_APP_APP_ID}
        REACT_APP_MEASUREMENT_ID: ${REACT_APP_MEASUREMENT_ID}
    container_name: plants_frontend
    restart: always
    ports:
      - "3001:80"
    depends_on:
      - plants-backend